"""esquema inicial

Revision ID: b3d98872572f
Revises: 
Create Date: 2026-09-05 16:18:14.950761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d98872572f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('parceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'FORNECEDOR', 'AMBOS', name='tipoparceiro'), nullable=False),
    sa.Column('tipo_pessoa', sa.Enum('FISICA', 'JURIDICA', name='tipopessoa'), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('documento', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parceiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parceiros_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_parceiros_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_parceiros_tipo'), ['tipo'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'GERENTE', 'OPERADOR', name='perfil'), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('salario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('caixa_sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'FECHADA', name='statuscaixa'), nullable=False),
    sa.Column('usuario_abertura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_fechamento_id', sa.Integer(), nullable=True),
    sa.Column('aberto_em', sa.DateTime(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('valor_abertura', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_informado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_esperado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('diferenca', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacao_abertura', sa.Text(), nullable=True),
    sa.Column('observacao_fechamento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ),
    sa.ForeignKeyConstraint(['usuario_abertura_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_fechamento_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caixa_sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caixa_sessoes_aberto_em'), ['aberto_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_caixa_sessoes_caixa_id'), ['caixa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caixa_sessoes_status'), ['status'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('unidade', sa.String(length=6), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['parceiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)

    op.create_table('registros_ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('entrada', sa.DateTime(), nullable=True),
    sa.Column('saida', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'data', name='uq_ponto_dia')
    )
    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_ponto_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_ponto_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('movimentos_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SANGRIA', 'SUPRIMENTO', name='tipomovimentocaixa'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['caixa_sessoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_caixa_sessao_id'), ['sessao_id'], unique=False)

    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('documento_cliente', sa.String(length=14), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('caixa_sessao_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'FINALIZADA', 'CANCELADA', name='statusvenda'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'DEBITO', 'CREDITO', 'PIX', 'FIADO', name='formapagamento'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('troco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_sessao_id'], ['caixa_sessoes.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['parceiros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_caixa_sessao_id'), ['caixa_sessao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_documento_cliente'), ['documento_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_status'), ['status'], unique=False)

    op.create_table('movimentos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'PERDA', name='tipomovimento'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('saldo_apos', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_produto_id'), ['produto_id'], unique=False)

    op.create_table('titulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PAGAR', 'RECEBER', name='tipotitulo'), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('parceiro_id', sa.Integer(), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('quitado_em', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'PARCIAL', 'PAGO', 'CANCELADO', name='statustitulo'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'DEBITO', 'CREDITO', 'PIX', 'FIADO', name='formapagamento'), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titulos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_titulos_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_titulos_vencimento'), ['vencimento'], unique=False)

    op.create_table('venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_itens')
    with op.batch_alter_table('titulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titulos_vencimento'))
        batch_op.drop_index(batch_op.f('ix_titulos_tipo'))
        batch_op.drop_index(batch_op.f('ix_titulos_status'))

    op.drop_table('titulos')
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_criado_em'))

    op.drop_table('movimentos_estoque')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_status'))
        batch_op.drop_index(batch_op.f('ix_vendas_documento_cliente'))
        batch_op.drop_index(batch_op.f('ix_vendas_criado_em'))
        batch_op.drop_index(batch_op.f('ix_vendas_caixa_sessao_id'))

    op.drop_table('vendas')
    with op.batch_alter_table('movimentos_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_caixa_sessao_id'))

    op.drop_table('movimentos_caixa')
    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_ponto_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_registros_ponto_data'))

    op.drop_table('registros_ponto')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_codigo'))

    op.drop_table('produtos')
    with op.batch_alter_table('caixa_sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caixa_sessoes_status'))
        batch_op.drop_index(batch_op.f('ix_caixa_sessoes_caixa_id'))
        batch_op.drop_index(batch_op.f('ix_caixa_sessoes_aberto_em'))

    op.drop_table('caixa_sessoes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('parceiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parceiros_tipo'))
        batch_op.drop_index(batch_op.f('ix_parceiros_nome'))
        batch_op.drop_index(batch_op.f('ix_parceiros_documento'))

    op.drop_table('parceiros')
    op.drop_table('categorias')
    op.drop_table('caixas')
    # ### end Alembic commands ###
